name: Create Zarf Package
description: Creates a Zarf package for the requested path

outputs:
  latest-package-version:
    description: The latest zarf package version
    value: ${{ steps.latest-package-version.outputs.latest-package-version }}

inputs:
  download-init-package:
    description: Include Zarf init package
    required: false

runs:
  using: composite
  steps:
    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main
      with:
        # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
        version: v0.29.2
        download-init-package: ${{ inputs.download-init-package }}

    - name: Create Zarf Package
      shell: bash
      run: zarf package create --confirm
